"""
Constants module initialization.
Exports all model features, API constants, and configuration values.
"""

from predictor.constants.model_features import (
    BASE_ANIMALS_FEATURES,
    BASE_BIRDS_FEATURES,
    BASE_INSECTS_FEATURES,
    BASE_PLANTS_FEATURES,
    BASE_ANIMALS_OCCURRENCE_FEATURES,
    FEATURE_SETS,
    OCCURRENCE_FEATURE_SETS,
    OTP_TTL_SECONDS,
    DEFAULT_N_CLUSTERS,
    DEFAULT_LIMIT_ITEMS,
    SPECIES_CACHE_KEYS,
    CLUSTERING_CACHE_KEYS,
    DEFAULT_PAGINATION_LIMIT,
    MAX_PAGINATION_LIMIT,
)

from predictor.constants.api_constants import (
    ERROR_INVALID_INPUT,
    ERROR_MODEL_NOT_LOADED,
    ERROR_FILE_NOT_FOUND,
    ERROR_PROCESSING_FAILED,
    ERROR_OTP_EXPIRED,
    ERROR_INVALID_OTP,
    ERROR_EMAIL_INVALID,
    ERROR_SMTP_NOT_CONFIGURED,
    SUCCESS_OTP_SENT,
    SUCCESS_VERIFIED,
    VALID_CATEGORIES,
    HTTP_OK,
    HTTP_CREATED,
    HTTP_BAD_REQUEST,
    HTTP_NOT_FOUND,
    HTTP_SERVER_ERROR,
    RESULT_KEYS,
    DEFAULT_PAGE_SIZE,
    MAX_PAGE_SIZE,
)

__all__ = [
    # Model features
    'BASE_ANIMALS_FEATURES',
    'BASE_BIRDS_FEATURES',
    'BASE_INSECTS_FEATURES',
    'BASE_PLANTS_FEATURES',
    'BASE_ANIMALS_OCCURRENCE_FEATURES',
    'FEATURE_SETS',
    'OCCURRENCE_FEATURE_SETS',
    
    # Configuration
    'OTP_TTL_SECONDS',
    'DEFAULT_N_CLUSTERS',
    'DEFAULT_LIMIT_ITEMS',
    'SPECIES_CACHE_KEYS',
    'CLUSTERING_CACHE_KEYS',
    'DEFAULT_PAGINATION_LIMIT',
    'MAX_PAGINATION_LIMIT',
    
    # API Messages
    'ERROR_INVALID_INPUT',
    'ERROR_MODEL_NOT_LOADED',
    'ERROR_FILE_NOT_FOUND',
    'ERROR_PROCESSING_FAILED',
    'ERROR_OTP_EXPIRED',
    'ERROR_INVALID_OTP',
    'ERROR_EMAIL_INVALID',
    'ERROR_SMTP_NOT_CONFIGURED',
    'SUCCESS_OTP_SENT',
    'SUCCESS_VERIFIED',
    
    # API Configuration
    'VALID_CATEGORIES',
    'HTTP_OK',
    'HTTP_CREATED',
    'HTTP_BAD_REQUEST',
    'HTTP_NOT_FOUND',
    'HTTP_SERVER_ERROR',
    'RESULT_KEYS',
    'DEFAULT_PAGE_SIZE',
    'MAX_PAGE_SIZE',
]